#index:
#    path: /
#    controller: App\Controller\DefaultController::index
circle:
  path: /circle/{radius}
  controller: App\Controller\CalculatorController::circle
  methods: GET

triangle:
  path: /triangle/{a}/{b}/{c}
  controller: App\Controller\CalculatorController::triangle
  methods: GET
